### ISSUE TITLE
BUG: When book details page is closed, all pages are closed 

### ISSUE THREAD

**Issue by songulabuzar** [songulabuzar/CS535-LibraryManagementSystem#19]

**Comment by mertbahadir** [comment]
Bu hatayı çözersek iyi olur. Çünkü hoca ya demo yaparken sadece bir kitap detail acıp gösteremeyiz. Onu kapatınca bütün pagelerin kapanması hoş olmayacak demoda. Zamanım olursa yardımcı olurum bende sana. Bugün iş geldi ona bakıyorum bu hafta zaman olmayabilir. Haberleşelim çözersen falan haberdar et beni.

**Comment by songulabuzar** [comment]
Fixed error by changing setDefaultCloseOperation flag as DISPOSE_ON_CLOSE
